# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lenin Yee
tagline:          'Software developer, among other things'
description:      'Software developer, among other things.'
url:              http://leninyee.com
baseurl:          /

author:
  name:           'Lenin Yee'
  url:            https://twitter.com/leninyee

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lenin
